FROM python:3.12-slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive \
    DISPLAY=:0 \
    PYTHONUNBUFFERED=1 \
    TZ=America/New_York

WORKDIR /tmp/promobot-dependencies

ADD https://bootstrap.pypa.io/get-pip.py .

COPY setup.py .

RUN apt update && apt install --no-install-recommends -y wget gnupg ca-certificates \
    && apt install --no-install-recommends -y \
    build-essential \
    rustc \
    cargo \
    libnss3 \
    libxcb1 \
    libffi-dev \
    libssl-dev \
    libglib2.0-0 \
    tzdata \
    unzip \
    libxml2-dev \
    libxslt-dev \
        && wget https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip \
        && unzip chromedriver_linux64.zip \
        && mv chromedriver /usr/local/bin/chromedriver \
        && chmod +x /usr/local/bin/chromedriver \
        && rm chromedriver_linux64.zip \
    && pip install -U pip \
    && pip install setuptools-rust \
    && ./setup.py egg_info \
    && sed -i '/^\[dev\]$/Q' *.egg-info/requires.txt \
    && pip install -r *.egg-info/requires.txt \
    && apt purge -y build-essential rustc cargo libffi-dev libssl-dev \
    && rm -rf /tmp/promobot-dependencies /var/lib/apt/lists/*
