name: Promobot dependencies

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.dep'
      - 'setup.py'
      - '.github/workflows/dep.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Login on dockerhub
      run: |
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWD }} docker.io

    - name: Build and push the Docker image
      run: |
        docker buildx build \
          -t leandro2r/promobot:latest-dep \
          --platform linux/amd64,linux/arm/v7 \
          -f Dockerfile.dep \
          --pull --push .
